### ISSUE TITLE
Stop date as an alternative to duration

### ISSUE THREAD

**Issue by erapade** [Microsoft/powerbi-visuals-gantt#11]
Sometimes it's more convenient to specify a stop date-time instead of a duration. This stop date shall as the start date-time have a resolution of at least seconds. The code change is self is quite easy, and I have done it my self, but the trick is to define how this should be implemented in the GUI. Shall it be 1) a property setting defining if a value represents duration or stop time, or shall it be 2) two different fields where you can choose one (and only one) of them.  Or 3) shall the current duration field be changed to Duration/StopTime and then the code determines if it's a duration or StopTime

My suggestion is (3) but I need some comments and maybe some code help for that since I'm far from native in java script

**Comment by ignatvilesov** [comment]
Hello @erapade 

Thanks for your feedback.
I like the third option too.

Are you going to prepare a pull request soon? Otherwise, we'll include this ticket to our backlog and implement soon.

Ignat Vilesov,
Software Engineer

Microsoft Power BI Custom Visuals
pbicvsupport@microsoft.com

**Comment by erapade** [comment]
This is not relevant for me anymore. For others I guess a quick-measure would be able to do the same. If you are not going to implement this by your own interest, it's ok for me to close this request

**Comment by erapade** [comment]
looks like this is implemented since a while back now, so I will close this
