### ISSUE TITLE
Start date doesn't accounted.

### ISSUE THREAD

**Issue by LuanFerreira88** [microsoft/powerbi-visuals-gantt#131]
Hi, i'm using the gantt visualization to manage the vacations periods in days, but when i visualize in Power BI, End Date doesn't represent the real date wich the vacation must end, analizing looks like the Start Date doesn't accounted for the task duration, wich make the vacation have one more day. Is possible to make the Start Date be day one(not Zero) for task durantion? Images for example.
The language in some parts is Brazilian Portuguese.

How show in the Gantt chart:
![taskgantt](https://user-images.githubusercontent.com/44641779/47789787-4f938900-dcf4-11e8-9704-392373d400e1.jpg)
The date the vacation must end according with HR table:
![taskgantt1](https://user-images.githubusercontent.com/44641779/47789835-6afe9400-dcf4-11e8-890f-cbf6e5ee9d57.jpg)

**Comment by camilabpj** [comment]
Hello dear, did you find the solution? I`m with the same problem. Thanks!

**Comment by LuanFerreira88** [comment]
Hello, how am i dealing with vacationsin the chart, so i write a comment in the char in BI to indicate wich the end date is the return day form vacation. But this maybe cause some misinterpretation. Waiting for some answer.

**Comment by dlwnz** [comment]
I have the same issue
Leave chart with - for instance a start date of 18/12 for 4 days duration means leave should end on the 21/12.  However the chart is showing the end date as 22/12.

![powerbileaveieeus](https://user-images.githubusercontent.com/45341241/48985023-43baab80-f168-11e8-9da4-76fc029daa16.PNG)

Any ideas how this can be resolved?
 (if no solution yes we can put a comment in the chart thanks Luan, but not ideal)

**Comment by helen508light** [comment]
@ LuanFerreira88 @camilabpj @dlwnz 

From the initial logic of the visual, duration is the addentum ( EndDate = StartDate + Duration). So, it doesn't match the total number of days from start date to end date. 

Thank you for your feedback. 
We'll consider your suggestions in the next versions of the visual.
