### ISSUE TITLE
Legend changes color after loading to Power BI report service

### ISSUE THREAD

**Issue by dlwnz** [microsoft/powerbi-visuals-gantt#134]
Hi there
Having created a report using slicers and the gantt charts (great visual btw) - the legends on the gantt chart changes color when loaded onto power BI report service.

How can I make the legend colors 'stick'?

In the following screenshot showing the two reports - the top area is from the Desktop version which shows Tauranga in red.
In the bottom (in Service), you can see it has changed to aqua.
![image](https://user-images.githubusercontent.com/45341241/49346001-0b2f4a80-f6f1-11e8-8149-80ad7dda6436.png)

On the format of the visual on the desktop it is set as follows:
![image](https://user-images.githubusercontent.com/45341241/49346091-2cdd0180-f6f2-11e8-9455-73a59a879913.png)

However after being published when I edit in there it shows up as the following:
![image](https://user-images.githubusercontent.com/45341241/49346079-0cad4280-f6f2-11e8-95cc-bc5dc5da1cbb.png)

Is there a way I can ensure my legends stay the same color as what is in the desktop report.
Appreciate any help. Thanks

**Comment by helen508light** [comment]
@dlwnz 
Thanks for your feedback.
Could you also send an .pbix report to pbicvsupport@microsoft.com ?

**Comment by g-tarantino** [comment]
What is the status of this?
I can see the color option has been removed from the visual. when would it be reinstated?

**Comment by zBritva** [comment]
@g-tarantino The update of the visual is going to production. ETA is next Monday (7/8/2019)
