### ISSUE TITLE
How to modify DATE to COUNT?

### ISSUE THREAD

**Issue by SeaDude** [microsoft/powerbi-visuals-gantt#136]
Hello,
Thank you for this awesome visual! Will you give me some direction on how I can edit the source to change the X axis from a DATE to a COUNT?

I want to show basic spatial overlaps / alignments, rather than time-based. Literally EVERYTHING stays the same, just instead of dates across the top, I need counts.

Example:
- Construction: Start: 1.3, End: 7.8, Duration: 6.5
- QA:                 Start: 2.5, End: 3.5, Duration: 1.0
- Compaction:  Start: 1.3, End: 5.3, Duration: 2.0
- Etc.

I don't know where to start in the source code to make these changes myself. Any guidance?

Thanks again!

**Comment by pbicvsupport** [comment]
Hi @SeaDude 
At, first take a look at gantt.ts and it's update() function. It is the main visual's method.
See the createTasks() method, there are the data convertion for each task. Now, visual requires valid Date in startDate field on initialize it with Date.now() (line 840). You need to rewrite convertion of this case. Also there the calculations for task.end.

For rewriting axis scaling please take a look at calculateAxis() method: xAxisProperties and it's getValueFn would be important for you.
 xAxisDateFormatter also need to be rewritten. For more information about valueFormatting see https://github.com/Microsoft/powerbi-visuals-utils-formattingutils/blob/master/docs/api/value-formatter.md
Also, use d3 v3 documentation, if you need more information about d3 axis and scales https://github.com/d3/d3-3.x-api-reference/blob/master/API-Reference.md

Also, the same scale (by digits) realizes in LinedotChart https://github.com/Microsoft/powerbi-visuals-linedotchart  Please, use it's codebase as an example
