### ISSUE TITLE
Rendering issue with new update

### ISSUE THREAD

**Issue by imd93shk** [microsoft/powerbi-visuals-gantt#153]
Was there any changes made to the Gantt Chart visual? 
Because now the charts have lines which are overlapping the text as seen in the image below.
This happens both in PowerBi Desktop and Online. 

![Capture](https://user-images.githubusercontent.com/25534360/60868252-4ec4d680-a235-11e9-9f88-d5fac991c61d.PNG)

**Comment by zBritva** [comment]
Hello, could you share the sample report without private data? Thanks!

**Comment by imd93shk** [comment]
> Hello, could you share the sample report without private data? Thanks!

**Comment by imd93shk** [comment]
Issue seem to occur when changing *Height* in *Task Settings* (Check the attached images)

![Capture2](https://user-images.githubusercontent.com/25534360/60871998-913de180-a23c-11e9-9f79-ae8a69863a46.PNG)
![Capture1](https://user-images.githubusercontent.com/25534360/60871999-913de180-a23c-11e9-9a64-90bb197c7232.PNG)

**Comment by AlexanderK79** [comment]
I had the same issue and fixed it... :-)

Original line:
//.attr("y", (task: GroupedTask) => Gantt.DefaultValues.TaskLineWidth + (task.id + 1) * this.getResourceLabelTopMargin()) //original


New line:
 .attr("y", (taskConfigHeight - this.viewModel.settings.taskLabels.fontSize) / 2) // y is a relative positioning

**Comment by imd93shk** [comment]
@AlexanderK79 Thank you for the fix. However, I am a noob and don't actually know where to change codes and stuff. So, just posting this issue so that the team is aware of it and fixes ii in the next update.

**Comment by AlexanderK79** [comment]
Maybe @zBritva can add it to the bugfix log?

**Comment by uve** [comment]
The fix was published to AppSource. It should reach the production environment July, 16
