### ISSUE TITLE
% Complete move to “100” when the actual value is “1”

### ISSUE THREAD

**Issue by wadalhag** [microsoft/powerbi-visuals-gantt#158]
Both progress bar and however window displays 100 if the value is 1, this behavior does do not occur if the value is more than 1 or less than 1. i.e it will work fine if the value is 0 or between 2 and 100  
![Screenshot](https://user-images.githubusercontent.com/26463389/60915712-941cee80-a29d-11e9-8b62-1a53dcd106b9.PNG)

**Comment by helen508light** [comment]
Has been fixed in release version 2.1.0
