### ISSUE TITLE
Issue with collapse/group bars

### ISSUE THREAD

**Issue by ferdinand2020** [microsoft/powerbi-visuals-gantt#160]
Hi,

I like the new update! 
But i have experienced that if task with a couple of legends grouped together where two of the legends has same start date, then only one of them is visualized, where i expect to see both, since one of them has a higher duration than the other, and therefore will continue afterwards.

Please see attached screenshot and test power bi file, where you can see the issue on Project 1 with the legend Project and Phase 1. Phase 1 is not showing due to same start date as Project legend.

Hope you will fix this.

![Screenshot 2](https://user-images.githubusercontent.com/52746253/60968334-18fb1d00-a31d-11e9-8612-ccab44af9be6.jpg)
![Screenshot 1](https://user-images.githubusercontent.com/52746253/60968336-18fb1d00-a31d-11e9-9d2a-c10584db5e00.jpg)
[Test Data.zip](https://github.com/microsoft/powerbi-visuals-gantt/files/3377363/Test.Data.zip)

**Comment by ferdinand2020** [comment]
Hi,

Any idea when this bug will be fixed, I have a customer that really need this very soon?

**Comment by helen508light** [comment]
This issue is in work now.
There is no ETA, but in the most optimistic plans it could rich prod after 3 weeks

**Comment by ferdinand2020** [comment]
Hi Elena,

Thanks for your answer, I have been away for vacation.
I could see you expect 3 weeks to be in prod from your answer, so I assume that will be in this week, is this something I can rely on still? 😊

Med venlig hilsen/Best regards
[cid:image001.png@01D55BE2.D7A10C10]
Peter Ferdinand Bruun[cid:image002.png@01D55BE2.D7A10C10]<https://www.linkedin.com/in/peter-ferdinand-jensen-45148346/>
Team Lead & Senior PPM Consultant
p: +45 60 21 58 14
m: pfj@projectum.com<mailto:pfj@projectum.com>
w: www.projectum.com<http://www.projectum.com/>
[cid:image002.png@01D55BE2.D7A10C10]<https://www.linkedin.com/company-beta/121947/>[cid:image003.png@01D55BE2.D7A10C10]<http://www.projectum.dk/en/about/sign-up-for-our-newsletter/>[cid:image004.png@01D55BE2.D7A10C10]<https://www.youtube.com/channel/UCPiCGv62HWH9L8kxWtFjlGw>[cid:image005.png@01D55BE2.D7A10C10]<http://www.projectum.dk/en/news/>

**Comment by helen508light** [comment]
@ferdinand2020 
I told about the most optimistic option...
We had added this issue to your backlog, but there is no ETA for now

**Comment by ferdinand2020** [comment]
Hi Elena

Thank you for the quick answer.

Med venlig hilsen/Best regards
[cid:image001.png@01D55BFF.D556A0B0]
Peter Ferdinand Bruun[cid:image002.png@01D55BFF.D556A0B0]<https://www.linkedin.com/in/peter-ferdinand-jensen-45148346/>
Team Lead & Senior PPM Consultant
p: +45 60 21 58 14
m: pfj@projectum.com<mailto:pfj@projectum.com>
w: www.projectum.com<http://www.projectum.com/>
[cid:image002.png@01D55BFF.D556A0B0]<https://www.linkedin.com/company-beta/121947/>[cid:image003.png@01D55BFF.D556A0B0]<http://www.projectum.dk/en/about/sign-up-for-our-newsletter/>[cid:image004.png@01D55BFF.D556A0B0]<https://www.youtube.com/channel/UCPiCGv62HWH9L8kxWtFjlGw>[cid:image005.png@01D55BFF.D556A0B0]<http://www.projectum.dk/en/news/>

**Comment by helen508light** [comment]
Hi, @ferdinand2020 
We had investigated this question.
Actually, it is not an issue.
U use the same Project Name and the same Start, **but don't use Task name(needed for difference)**.
Legend field is not used in grouping.
Rows can be grouped by such fields: Task, Parent, StartDate, Resource, ExtraInformation, Milestones.

**So, there are no difference between this 2 rows for power BI**, because in this visual used grouping by category(Task field and Start Date in your case).

You may use parent-child structure: Task field is Task name and Parent field is Project Name. But it has different picture(one row for pre child)
The second way is DAX Queries usage - u can merge 2 fields in one(Task Name + Project Name) and the use this merged field to achieve your goal
