### ISSUE TITLE
Problems with horizontal grey lines in new update

### ISSUE THREAD

**Issue by nicola-dragoni** [microsoft/powerbi-visuals-gantt#161]
So, after the recent update (v2.0.0) I found these weird grey bars in my gantt chart.

![image](https://user-images.githubusercontent.com/52753209/60982652-d8110180-a338-11e9-9131-29613a7b74f9.png)

After playing around with the settings, I realized that they line up very nicely with the activities in the gantt, provided that you choose the standard activity height in the format pane (the standard value is 40).

However, for my gantt, this is not acceptable.

Is there a way to turn off this setting?

**Comment by imd93shk** [comment]
Hi @nicola-dragoni , I had the same issue which someone recommended a solution to. Check the following link for the recomendation.

https://github.com/microsoft/powerbi-visuals-gantt/issues/153

**Comment by nicola-dragoni** [comment]
Hi @imd93shk , I see that it seems to be fixed.

However I am not sure on how to get the updated version.

On PowerBI Desktop I can only see the 2.0.0 version.
Am I supposed to build the visual from the code?

**Comment by imd93shk** [comment]
@nicola-dragoni I have no idea how to update/make the changes and I don't think version 2.0.3 has been uploaded to Microsoft Store Marketplace.

**Comment by nicola-dragoni** [comment]
@imd93shk Thank you.

I guess I will try to follow the Microsoft guide or wait for them to push the update.

**Comment by uve** [comment]
The fix was published to AppSource. It should reach the production environment July, 16
