### ISSUE TITLE
Problems with new update

### ISSUE THREAD

**Issue by MrLock0107** [microsoft/powerbi-visuals-gantt#162]
Good evening, I really like the new update.
I found some malfunctions that I point out below:
1) Legend: It conflicts if it finds a description with a parenthesis eg: "Delay (> 10%)" - the BAR remains black, "Delay> 10%" - the BAR changes color.
2) Finish Date: If you enter the field in the Finish Date the legend for changing the colors does not activate but is only activated if the Duration is entered.
3) Duration: In some cases the days are incorrectly calculated in the bar chart and in the tooltip.

Thank's # #

**Comment by pfwp78** [comment]
I am also having problems with the % complete bar.  I assume the shading has replaced the horizontal line, but it is not accurate at all - i.e. some activities that have 0% completion are fully or partially shaded, etc.

**Comment by pedro-cf** [comment]
With the new update the style on my tasks radically changed from rectangles to rounded boxes... also the background  & task names are different. Is there no way to keep the old style ?

**Comment by pfwp78** [comment]
Example in the image below - in the 6th line down the first box is shaded to 27% complete, which is correct, but then the second box on that line which is 0% complete is shaded the same.  And you can see most of the tasks that haven't started yet are shaded 100% complete.

![image](https://user-images.githubusercontent.com/52796770/61220367-c97d6e00-a6db-11e9-9f3e-9cfab22985ad.png)

**Comment by MrLock0107** [comment]
News for the next release?

**Comment by pfwp78** [comment]
> News for the next release?

@MrLock0107 I was told that the % complete issue would be resolved in the next release on 8/13.  Not sure about the other issues.

**Comment by MrLock0107** [comment]
Ok thank you

**Comment by helen508light** [comment]
**Bar color issue**, issue with  **completion for different bars from one line** and **Legend usage only with Duration** issue has been fixed in the next release.

**Comment by MrLock0107** [comment]
With Versione 2.1.x? Thank's

**Comment by helen508light** [comment]
yep

**Comment by helen508light** [comment]
@MrLock0107 
Could you please provide the report for reproducing incorrect evaluatioon of duration cases?
U can attach it here or sent to pbicvsupport@microsoft.com

**Comment by MrLock0107** [comment]
> @MrLock0107
> Could you please provide the report for reproducing incorrectly calculated duration issue?
> U can attach it here or sent to [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com)

Step 1: Not yet verified

Step 2: KO (View images)

![CatturaGantt](https://user-images.githubusercontent.com/52703510/62617456-2f8f9680-b912-11e9-9ad7-35aaf325b35a.PNG)

![CatturaLegenda](https://user-images.githubusercontent.com/52703510/62617527-5b128100-b912-11e9-9c56-4f36d0d64b45.PNG)

Step 3: It would seem OK

**Comment by pbicvsupport** [comment]
Hi @MrLock0107 @pfwp78 @pedro-cf
Is this issue still reprodicable for you?
Please note, we had released new 2.2.3 version on prod

**Comment by MrLock0107** [comment]
> Ciao @ MrLock0107 @ pfwp78 @ pedro-cf
> Questo problema è ancora riproducibile per te?
> Si noti che avevamo prodotto la nuova versione 2.2.3 su prod

OK for all!!! Thank's
