### ISSUE TITLE
Legend Colors Not Consistent With Graph

### ISSUE THREAD

**Issue by pfwp78** [microsoft/powerbi-visuals-gantt#178]
The bars on my Gantt chart are suddenly not matching to the appropriate color in the legend.  They also change just about every time I refresh.

**Comment by helen508light** [comment]
We had faced with the same issue an it has already been fixed by last PR from this repo.
But this changes has not been released yet.
For fast fix u can build package from last PR with changed GUID by yourself  and then use it

**Comment by pfwp78** [comment]
Can you instruct me on how to build the package from the last PR?

Sent from my iPhone

On Sep 26, 2019, at 4:03 AM, Elena Rodionova <notifications@github.com<mailto:notifications@github.com>> wrote:


We had faced with the same issue an it has already been fixed by last PR from this repo.
But this changes has not been released yet.
For fast fix u can build package from last PR with changed GUID by yourself and then use it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_powerbi-2Dvisuals-2Dgantt_issues_178-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAMSZ2YTMVI4GPKYX7RHI74TQLR3D5A5CNFSM4I2R26K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7U3W6I-23issuecomment-2D535411577&d=DwMCaQ&c=7wahE4Ax3UWYSiYx9QiKrg--tBTc2YU0w8SAd8ppZuE&r=0BmF3vAQi5xPFHrrvwsY93nDrzbpG-KI62qjc-S4-vg&m=-3IN2qaAnodZ1RcG4f-gBl43jh20MhxsqBOTKbHpLx0&s=4cRGjCubTgpzm568Zyl64CJM8aBGQPFh72QmeTf_S7E&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMSZ2YTD3YOQA4FXOPSKWHTQLR3D5ANCNFSM4I2R26KQ&d=DwMCaQ&c=7wahE4Ax3UWYSiYx9QiKrg--tBTc2YU0w8SAd8ppZuE&r=0BmF3vAQi5xPFHrrvwsY93nDrzbpG-KI62qjc-S4-vg&m=-3IN2qaAnodZ1RcG4f-gBl43jh20MhxsqBOTKbHpLx0&s=wH_r9t-WpGPoxmoQgW-9deoykMcmndXLx5_7E4hngmE&e=>.

CONFIDENTIALITY NOTICE: This e-mail, including any attachments, is for viewing and use solely by the intended recipient(s), and may contain confidential, privileged and/or proprietary information. If you have or believe that you may have received this e-mail in error, please contact the sender immediately by replying to this email and please permanently delete all copies of this email, including any sent (reply) copy, from your computer. The sender can also be contacted by telephone at (254) 776-3722.

**Comment by helen508light** [comment]
Please install git on your machine and follow steps 1-6.
After it u need to change guid in downloaded project's pbiviz.json file. 
Install Prerequisites from here https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial
Run "npm i" and then then try "npm run package" from project's folder ->get new pbiviz file in dist folder -> attach it to powerbi service by clicking there 
![image](https://user-images.githubusercontent.com/12563593/65873611-3673dc00-e38c-11e9-8f1c-717f13b3961d.png)

**Comment by helen508light** [comment]
Now we had reverted Gantt to working 2.0.2 issue, so u shouldn't do anything
