### ISSUE TITLE
Changes are not reflecting after Packaging

### ISSUE THREAD

**Issue by 123jomy** [microsoft/powerbi-visuals-gantt#189]
Hi ,
I have made some changes in Gantt Chart custom visual code base. Added two new columns and added required code to populate from the dataset. It is working as expected in power BI web version as expected. 
I tried to make it as a package by using the command pbiviz package . After packaging I have tried to import it to the Power BI desktop. But unfortunately the newly added columns and fields are not displaying.

Please let me know if you have any idea about this issue. 

![image](https://user-images.githubusercontent.com/55131669/68649831-8b724880-051b-11ea-82b7-86189a8580a4.png)

**Comment by pbicvsupport** [comment]
You should change GUID in pbiviz.json and build the package with changed guid, because now it imports package from our cdn with the same guid.

**Comment by helen508light** [comment]
You should change GUID in pbiviz.json and build the package with changed guid, because now it imports package from our cdn with the same guid.

**Comment by 123jomy** [comment]
Thank you

**Comment by Minituff** [comment]
@123jomy Can you share the code that helped you add multiple columns. I am tryin to figure this out now.
