### ISSUE TITLE
Modify Gantt Date type

### ISSUE THREAD

**Issue by slc7456** [microsoft/powerbi-visuals-gantt#19]
I would like to modify the Gantt chart to allow for Gantt Date types Hour and 15minutes. 

Can you point me in the right direction on what I would need to update to allow this functionality?

**Comment by erapade** [comment]
I'm trying to get this as well. You shall know that the current minimal duration is 24 hours. Start time is having the accuracy of seconds, but durations is always an multiple of 24 hours. You can read [my comments](https://github.com/Microsoft/powerbi-visuals-gantt/pull/10) on this pull request where I tried to remove the 24 hour duration limitation. 


I guess your change would be quite easy. In Gantt.ts you need to do the following
Add Hours, Minutes, seconds (my request), as well as Quaters (15 minutes) below
```
103     const MillisecondsInADay: number = 24 * 60 * 60 * 1000; 
104     const MillisecondsInWeek: number = 4 * MillisecondsInADay; 
105     const MillisecondsInAMonth: number = 30 * MillisecondsInADay; 
106     const MillisecondsInAYear: number = 365 * MillisecondsInADay; 
```

 
Also prepare this for Hours, Quaters, Minutes, and seconds
```
784         private static getDateType(dateType: string): number { 
785             switch (dateType) { 
786                 case "Day": 
787                     return MillisecondsInADay; 
788 
789                 case "Week": 
790                     return MillisecondsInWeek; 
791 
792                 case "Month": 
793                     return MillisecondsInAMonth; 
794 
795                 case "Year": 
796                     return MillisecondsInAYear; 
797 
798                 default: 
799                     return MillisecondsInWeek; 
800             } 
```
You also need to implement my suggested change by replacing day with second below:
```
592                         task.end = d3.time.day.offset(task.start, task.duration); 
```

Probably also change here:
```
244             DateFormatStrings: { 
245                 Day: "MMM dd", 
246                 Week: "MMM dd", 
247                 Month: "MMM yyyy", 
248                 Year: "yyyy" 
249             } 
```

And in Settings.ts You probably need to change this:

`30     export type GanttDateType = "Day" | "Week" | "Month" | "Year"; `

But I don't no anything about writing TypeScript or Java Script, so there could be more as well. I'm currently not the admin on my computer so I cant compile. If anyone does this change, please let me have a copy

**Comment by erapade** [comment]
I guess this can be closed now since we can have seconds, minutes, hours, and days. But I guess that slc7456 shall confirm first
