### ISSUE TITLE
Custom gantt chart compile issue

### ISSUE THREAD

**Issue by smilekudo** [microsoft/powerbi-visuals-gantt#198]
Hi,
I want to custom text on tooltips and change icon for Gantt 2.2.3 what i get from market place.
I tried to install following this guide: https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial

But when i tried to start viz from github (gantt), they show me error when compile, so i can't customize for myself.
Please help me fix this.

Here is log:
`PS C:\PBICustom\rosedaleGantt> pbiviz start                                                                                                                           
 info   Starting server...
 info   Start preparing plugin template
i ｢wds｣: Project is running at https://localhost:8080/webpack-dev-server/
i ｢wds｣: webpack output is served from /assets
i ｢wds｣: Content not from webpack is served from C:\PBICustom\rosedaleGantt\.tmp\drop
 info   Finish preparing plugin template
Webpack Bundle Analyzer saved report to C:\PBICustom\rosedaleGantt\webpack.statistics.dev.html

 ERROR  Failed to compile with 3 errors                                                                                                                     4:56:12 PM

 error  in C:\PBICustom\rosedaleGantt\src\gantt.ts

[tsl] ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts(83,29)
      TS2694: Namespace '"C:/PBICustom/rosedaleGantt/node_modules/powerbi-visuals-utils-formattingutils/lib/src/textMeasurementService".textMeasurementService' has no exported member 'TextProperties'.

 error  in C:\PBICustom\rosedaleGantt\src\gantt.ts

[tsl] ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts(85,37)
      TS2339: Property 'textMeasurementService' does not exist on type 'typeof textMeasurementService'.

 error  in C:\PBICustom\rosedaleGantt\src\gantt.ts

[tsl] ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts(85,37)
      TS2694: Namespace '"C:/PBICustom/rosedaleGantt/node_modules/powerbi-visuals-utils-formattingutils/lib/src/textMeasurementService".textMeasurementService' has no exported member 'textMeasurementService'.

× ｢wdm｣: Hash: 0fdf315a663173b7bf35
Version: webpack 4.39.2
Time: 14354ms
Built at: 02/04/2020 4:56:12 PM
                                     Asset       Size  Chunks  Chunk Names
..\build\.tmp\precompile\visualPlugin.d.ts  223 bytes
                ..\build\src\behavior.d.ts   1.48 KiB
                 ..\build\src\columns.d.ts  649 bytes
             ..\build\src\drawButtons.d.ts  496 bytes
          ..\build\src\durationHelper.d.ts  926 bytes
                   ..\build\src\gantt.d.ts   12.9 KiB
              ..\build\src\interfaces.d.ts   3.81 KiB
                ..\build\src\settings.d.ts   1.98 KiB
                   ..\build\src\utils.d.ts  871 bytes
                                visual.css   4.92 KiB       0  visual.js
                            visual.css.map   5.87 KiB       0  visual.js
                                 visual.js   4.14 MiB       0  visual.js
                             visual.js.map   8.68 MiB       0  visual.js
Entrypoint visual.js = visual.css visual.js visual.css.map visual.js.map
  [9] ./node_modules/powerbi-visuals-utils-typeutils/lib/index.js 966 bytes {0} [built]
 [14] ./node_modules/lodash/lodash.js 467 KiB {0} [built]
 [42] ./src/gantt.ts 110 KiB {0} [built] [3 errors]
 [53] ./node_modules/d3/index.js 891 bytes {0} [built]
 [63] ./src/utils.ts 2.58 KiB {0} [built]
 [64] external "Function('return this')()" 42 bytes {0} [built]
 [82] ./node_modules/powerbi-visuals-utils-chartutils/lib/index.js 1.29 KiB {0} [built]
[103] ./node_modules/powerbi-visuals-utils-svgutils/lib/index.js 361 bytes {0} [built]
[177] ./node_modules/powerbi-visuals-utils-colorutils/lib/index.js 887 bytes {0} [built]
[178] ./src/durationHelper.ts 7.52 KiB {0} [built]
[179] ./src/drawButtons.ts 2.21 KiB {0} [built]
[215] ./node_modules/powerbi-visuals-utils-formattingutils/lib/src/index.js 1000 bytes {0} [built]
[368] ./src/settings.ts 6.09 KiB {0} [built]
[837] multi ./.tmp/precompile/visualPlugin.ts 28 bytes {0} [built]
[838] ./.tmp/precompile/visualPlugin.ts 665 bytes {0} [built]
    + 1673 hidden modules

ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts
./src/gantt.ts
[tsl] ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts(83,29)
      TS2694: Namespace '"C:/PBICustom/rosedaleGantt/node_modules/powerbi-visuals-utils-formattingutils/lib/src/textMeasurementService".textMeasurementService' has no exported member 'TextProperties'.

ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts
./src/gantt.ts
[tsl] ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts(85,37)
      TS2339: Property 'textMeasurementService' does not exist on type 'typeof textMeasurementService'.

ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts
./src/gantt.ts
[tsl] ERROR in C:\PBICustom\rosedaleGantt\src\gantt.ts(85,37)
      TS2694: Namespace '"C:/PBICustom/rosedaleGantt/node_modules/powerbi-visuals-utils-formattingutils/lib/src/textMeasurementService".textMeasurementService' has no exported member 'textMeasurementService'.
Child mini-css-extract-plugin ../../Users/Admin/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/css-loader/dist/cjs.js!../../Users/Admin/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js??ref--6-2!style/gantt.less:
    Entrypoint mini-css-extract-plugin = *
    [0] C:/Users/Admin/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/css-loader/dist/cjs.js!C:/Users/Admin/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/less-loader/dist/cjs.js??ref--6-2!./style/gantt.less 5.24 KiB {0} [built]
    [1] C:/Users/Admin/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/css-loader/dist/runtime/api.js 2.61 KiB {0} [built]
i ｢wdm｣: Failed to compile.`

**Comment by smilekudo** [comment]
Please remove this issue, that's my mistake, i could download and completed compile.

**Comment by kion-pr** [comment]
Hello! 
i'm new here and i've tried installing and running the visualization, but i'm getting the same errors as mentioned by @smilekudo  
viz., the ones with textMeasurementService and textProperties. i managed to resolve the former by modifying the line in the index.d.ts file from:
import { textMeasurementService } from "./textMeasurementService";
to:
import * as textMeasurementService  from "./textMeasurementService"; 

but how do i fix the issue with the textProperties? from what i've understood so far, the parameter textProperties is used within individual methods but is never returned. should that be added here? 

please help. thanks in advance! :)
