### ISSUE TITLE
Highlighting Linked Tasks

### ISSUE THREAD

**Issue by JMN79** [microsoft/powerbi-visuals-gantt#202]
Hi Team,

Is there any existing method to highlight a linked task within the gantt so you can view dependencies?

I.e. Task A is linked to task B so visually display that relationship?

If not is there anything in the pipeline for this?

Many thanks

Jarrod

**Comment by helen508light** [comment]
@JMN79 now for this goal you can use only Task type or create an hierarchy with parent task and related children

**Comment by helen508light** [comment]
@JMN79
If this way doesn't fit you, please describe with details and pictures what do you exactly want to have
