### ISSUE TITLE
Feature Request: Grouping of tasks

### ISSUE THREAD

**Issue by aersamkull** [microsoft/powerbi-visuals-gantt#25]
We have a client that likes to group his tasks by Levels (eg. Functional / Non-Functional / Administrative Tasks)

That would be a very nice addition to the Gantt Chart :)

**Comment by djouallah** [comment]
it is a pretty standard request, it is very rare to show only tasks, you need always to do some grouping

**Comment by dryburghi** [comment]
We also have a request from users to have this feature...

**Comment by uve** [comment]
Hello @aersamkull, @djouallah, @dryburghi.
Thank you for your feedback.
We'll plan to add Grouping of tasks to one of the following Gantt versions.

**Comment by BrettThompson83** [comment]
I am curious to know if there is a plan yet to have grouping available in this visual? Fantastic work on this visual, it has been very helpful for us and we really appreciate the efforts!!

**Comment by BrettThompson83** [comment]
I am curious to know if there is a plan yet to have grouping available in this visual? Fantastic work on this visual, it has been very helpful for us and we really appreciate the efforts!!

**Comment by helen508light** [comment]
Now it's able to group tasks by type - you need to use General formatting option GroupTask ="ON"
