### ISSUE TITLE
API Versioning Issue

### ISSUE THREAD

**Issue by Astral-Iris** [microsoft/powerbi-visuals-gantt#273]
I would like to modify this visual. Without changing anything in the code, when I run "pbiviz start", I get an error "Can't start the visual because of the current API is '2.6.0'." I've tried everything I can google to try to get fix this error, but nothing is working. Does anyone have an updated version of the source code, or can you provide guidance to correct this error?

**Comment by geromble** [comment]
How did you fix this issue?
