### ISSUE TITLE
Tooltip Limit

### ISSUE THREAD

**Issue by hypnoticmt** [microsoft/powerbi-visuals-gantt#343]
Is there a way to increase the number of tooltips on the visual? I believe the limit on tooltips is set to 3.

**Comment by MulyukovAidar** [comment]
Hello, what do you mean by _limit of tooltips_?

**Comment by James-Andrade** [comment]
Hi. I believe @hypnoticmt is referring to is that you can drag a max 3 columns into tooltips role (in the visualizations > build visual area). Fixing this likely only requires modifying the dataViewMappings section of the capabilities.json file.

**Comment by hypnoticmt** [comment]
Exactly as @James-Andrade mentioned. Managed to fix it by modifying the capabilities.json file.
