### ISSUE TITLE
Fix Task Pane

### ISSUE THREAD

**Issue by googlogmob** [microsoft/powerbi-visuals-gantt#4]
Please, fix task pane
http://prntscr.com/dw7d63

Now  task pane moves and disappears with horizontal scrolling taskbar
http://prntscr.com/dw7dbh

**Comment by ignatvilesov** [comment]
Hello @googlogmob 

Thanks for your feedback.
We'll address and fix this issue soon

**Comment by SamVDV** [comment]
Please fix also the timeline at the top (which disappears with vertical scrollbar)

**Comment by maneshd5** [comment]
I was wondering if anyone has had success recently in creating a Gantt chart like the image below where the task names are sorted alphabetically? I've done this in the past by adding the values into the fields a certain way but not able to replicate. Thanks.

![6-22-2017 9-27-07 am](https://user-images.githubusercontent.com/29631836/27440493-9498ea68-5730-11e7-972d-f931ed71c301.png)

**Comment by helen508light** [comment]
Task pane & scrollbar are already fixed
