### ISSUE TITLE
Feature Request: Show Milestones

### ISSUE THREAD

**Issue by bebetech** [microsoft/powerbi-visuals-gantt#72]
Needs to be able to show 0-day tasks such as milestones. Having a different image (e.g. diamond) would be even better.

**Comment by albertofilho82** [comment]
I would suggest a milestone category, so users could assign different labels (or images) to those milestones. 

@ignatvilesov

**Comment by uve** [comment]
GanttChart v2 supports Milestones now.

**Comment by jagrock** [comment]
I see the option in the filter, but there is no documentatoin on what is expected.  It only allows one date field and adding a date here removes the filled bar and adds vertical lines similar to the current date line.

**Comment by helen508light** [comment]
For milestones usage u need to:
- add one Field to Milestone bucket
- the Field must include string data that means each milestone type(some may be empty)
- it would be applied to all tasks
- if task has duration = 0, startDate and it's row in Milestone field is not empty - task would be interpreted as milestone, so it would be vertical line with shape. 
- task with empty Milestone row is interpreted as regular task

**Comment by helen508light** [comment]
This feature has explanation in sample report and it's **Milestones and common bar** and **Hints** section
