### ISSUE TITLE
Cannot sort data anymore

### ISSUE THREAD

**Issue by jackburton79** [Microsoft/powerbi-visuals-gantt#75]
Since some time, it's not possible to order data in the Gantt visual.
It used to be possible by clicking on the options menu (this one:)
![immagine](https://user-images.githubusercontent.com/3501519/31708459-544534dc-b3ef-11e7-804f-1e14adf39ccd.png)

But this option is no longer available.
Unfortunately, the Gantt visual component ignores any order set on the data.

**Comment by uve** [comment]
Hello @jackburton79,
 We'll add a sorting option into the next version of GanttChart.

**Comment by jackburton79** [comment]
Thanks a lot! Do you have a timeframe for the next version ?

**Comment by jackburton79** [comment]
Any news on this one ?
Thanks!

**Comment by uve** [comment]
@jackburton79, current version of Gantt Chart supports sorting data.
