### ISSUE TITLE
Somehow taskbars are not showing after publishing

### ISSUE THREAD

**Issue by HarPuIt** [Microsoft/powerbi-visuals-gantt#77]
Today I implemented the Gantt in my Power BI tool, and I looks pretty nice. After publishing the dashboard the chart does not show the task bars anymore... Is this a bug?
In tool:
![capture_in_tool](https://user-images.githubusercontent.com/33234177/32191350-1466d4d0-bdb1-11e7-930e-33539680f8b0.PNG)
Online:
![capture_online](https://user-images.githubusercontent.com/33234177/32191351-14a0efda-bdb1-11e7-9c79-fa5b31aa58e6.PNG)

**Comment by uve** [comment]
thanks @HarPuIt for your report. It's bug, we'll check it.

**Comment by savvinsergey** [comment]
Could you say me duration of these tasks and what value of "General -> Duration Min" setting?

**Comment by HarPuIt** [comment]
Dear Sergey,
Please let me test some things with the duration first. Because probably I did somethin wrong there!
I will update you asap.
Regards,
Harold

**Comment by joaod** [comment]
Hi! I'm getting exactly the same issue. Additionally, in my case the problem exists in both tools, client and online. Maybe this could be a bug after some recent Power BI recent update?

**Comment by HarPuIt** [comment]
Somehow it is confusing for me how it works. What do I actually need to provide for duration. I added an example to this message.

[testgantt.zip](https://github.com/Microsoft/powerbi-visuals-gantt/files/1457601/testgantt.zip)

**Comment by uve** [comment]
@joaod, @HarPuIt The fix for this bug is ready and it will be included into the next version of Gantt Chart.

**Comment by HarPuIt** [comment]
Great! Thank you for this service!

**Comment by mvgaliev** [comment]
Hello @joaod, @HarPuIt! Can you still reproduce this issue? I've tried testgantt.zip. Pinning to dashboard works smoothly.

**Comment by HarPuIt** [comment]
@mvgaliev: Uve said that this will be fixed in the new release in December. In my case it has probably something to setting a wrong value for duration, but unfortunately I couldn't find the time to work it until now.
