### ISSUE TITLE
Duration seems wrong

### ISSUE THREAD

**Issue by Edge4711** [microsoft/powerbi-visuals-gantt#83]
I used the visual with Aug 1, 2017 as start date with 60 days Duration (I am assuming that these are workdays??) ... I expanded the visual out and the bar stops on Dec 09, 2017

Consider start date Aug 1, 2017 and  end date 9 December, 2017,
Using excel function networkdays()  tells me that there is 84 work days between, and there is 130 days between including weekends.

I noticed that this is wrong because %Complete is always behind today ...
i.e Say a task takes 10 days ... and I am 5 days complete and mark %Completion at .5 (50%) then it still doesnt reach today

**Comment by Edge4711** [comment]
Duration is tricky in projects due to weekends, holidays etc etc 
IMHO start date , end date is cleaner and less error prone,
however my understanding may well be flawed ... Great APP BTW

**Comment by uve** [comment]
Thank you @Edge4711, for your feedback. We'll consider your suggestion in the next versions of the visual.

**Comment by helen508light** [comment]
we changed duration and holidays calculation in last versions
