### ISSUE TITLE
Tasks with duration less than a day don't show on the chart

### ISSUE THREAD

**Issue by janeztr** [Microsoft/powerbi-visuals-gantt#91]
Hi,
Tasks with duration less than a day are left blank on the chart.
![image](https://user-images.githubusercontent.com/31987982/34128949-a253301a-e442-11e7-8efd-67ec56e06754.png)
![image](https://user-images.githubusercontent.com/31987982/34129003-ccdbb424-e442-11e7-8330-17c35e0fcf17.png)

Regards,
Janez

**Comment by ignatvilesov** [comment]
Thank you for reporting this issue.
We'll look into it and prepare a fix.

**Comment by albertofilho82** [comment]
When start and end date are the same, duraiton field on tooltip shows "false days" instead of "1 day". And a thin bar should be shown instead of nothing.

![print](https://user-images.githubusercontent.com/37080912/36989002-2a9463f4-207f-11e8-9477-a81ba8170182.png)

**Comment by ignatvilesov** [comment]
@albertofilho82 Thank you for reporting the issue.
We'll consider it in upcoming version of Gantt

**Comment by albertofilho82** [comment]
BTW, I notice that there is a version 1.9.3 avalilable on git, but it's not on Microsoft Store for download. How can I get the latest version? @ignatvilesov

**Comment by ignatvilesov** [comment]
@albertofilho82 Gantt 1.9.3 was submitted to App Source fro review and approval yesterday.
Hopefully it will be approved soon and it will be available for end-users in about 2 weeks or so.

**Comment by helen508light** [comment]
These issues have already been fixed
