### ISSUE TITLE
Chart doesn't stretch to fill window - a problem for multiple activities within a day

### ISSUE THREAD

**Issue by HairyDrumroll** [Microsoft/powerbi-visuals-gantt#96]
Hi, Thanks for continuing your work on this!
I'm looking at a 1 to 14 day horizon of events with up to 20 events per day. 
Unfortunately, even if I make the visualisation frame as wide as the report page, if there is only a few days of activity in my data set it all gets squished in to the top left corner. 
Is there any possibility for the distribution of days across the top to be scaled to fill the width of the frame?
![image](https://user-images.githubusercontent.com/13739294/35548500-c46bf1f6-05cf-11e8-997c-94ab1ed4dcbb.png)
Thanks again for your work.

HD.

**Comment by uve** [comment]
yes, I agree that Gantt Chart doesn't look very well when time period is short.
The most common scenario for this visual is when a user has a long time period and uses horizontal scrollbar to switch between dates.
So, currently, we don't mix horizontal scrollbar and auto-stretching.
We plan to improve this scenario in the next version of the visual.

**Comment by kevinob11** [comment]
When do you expect that update to land?

**Comment by uve** [comment]
@kevinob11, there is no ETA for this change for now.

**Comment by HairyDrumroll** [comment]
Any ETA?
> The most common scenario for this visual
I would suggest this visualisation gets used in many different ways.

**Comment by HairyDrumroll** [comment]
Seems to be working as expected now!
