### ISSUE TITLE
Tooltip doesn't work in Power BI Service

### ISSUE THREAD

**Issue by dooger21** [Microsoft/powerbi-visuals-gantt#98]
Tooltips work well in Power BI Desktop however when publishing the report the tooltips stop working as they should. To be clear attached an image in which is observed as the content of the tooltip does not change when moving the cursor to another task of the graph.

Please help us understand and discover why this error is due.
![issue pbi](https://user-images.githubusercontent.com/29255904/36951882-b53d23e6-1fd6-11e8-88b8-8a8334e35efd.png)

**Comment by uve** [comment]
Hello @dooger21, it's know issue and we plan to update Gantt visual in 2 weeks.

**Comment by dooger21** [comment]
Thanks a lot! Could you please tell me why is it issue?

**Comment by uve** [comment]
it looks like there is some regression after latest portal update

**Comment by dooger21** [comment]
The tooltips stop working when the scroll bars of the gantt object are displayed.

**Comment by helen508light** [comment]
This issue has already been solved
